In [1]:
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)
warnings.filterwarnings('ignore',category=DeprecationWarning)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate, KFold, RepeatedKFold, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.inspection import permutation_importance
import time
import xgboost as xgb

In [2]:
data = pd.read_csv("output.csv")
df = data.drop(['Time'], axis=1)
number_of_houses = len(df.columns)
df

       PT41CV  PT44AL  PT15VP  PT69QG  PT43QL  PT17RW  PT87ZW
0       0.028   0.452   0.000   0.828   0.128   0.056   0.552
1       0.080   0.440   0.000   0.796   0.160   0.056   0.492
2       0.092   0.424   0.000   0.832   0.220   0.056   0.308
3       0.040   0.408   0.000   0.800   0.404   0.088   0.156
4       0.076   0.396   0.000   0.836   0.156   0.116   0.160
...       ...     ...     ...     ...     ...     ...     ...
35027   0.120   0.448   0.108   0.220   0.164   0.144   0.368
35028   0.036   0.424   0.124   0.252   0.228   0.164   0.396
35029   0.064   0.392   0.148   0.268   0.224   0.220   0.356
35030   0.132   0.260   0.132   0.276   0.212   0.176   0.392
35031   0.180   0.332   0.088   0.288   0.148   0.132   0.356

[35032 rows x 7 columns]

In [3]:
data['Time']

0        2021-11-01 00:15:00
1        2021-11-01 00:30:00
2        2021-11-01 00:45:00
3        2021-11-01 01:00:00
4        2021-11-01 01:15:00
                ...
35027    2022-10-31 23:00:00
35028    2022-10-31 23:15:00
35029    2022-10-31 23:30:00
35030    2022-10-31 23:45:00
35031    2022-11-01 00:00:00
Name: Time, Length: 35032, dtype: object

In [4]:
house_list = []
test = data['Time']
for i in df:
    test = pd.concat([test, df[i]], axis=1)
    test = test.rename(columns={i: 'Energy'})
    test['Location'] = i
    house_list.append(test)

In [5]:
house_list

[                      Time  Energy Location
 0      2021-11-01 00:15:00   0.028   PT41CV
 1      2021-11-01 00:30:00   0.080   PT41CV
 2      2021-11-01 00:45:00   0.092   PT41CV
 3      2021-11-01 01:00:00   0.040   PT41CV
 4      2021-11-01 01:15:00   0.076   PT41CV
 ...                    ...     ...      ...
 35027  2022-10-31 23:00:00   0.120   PT41CV
 35028  2022-10-31 23:15:00   0.036   PT41CV
 35029  2022-10-31 23:30:00   0.064   PT41CV
 35030  2022-10-31 23:45:00   0.132   PT41CV
 35031  2022-11-01 00:00:00   0.180   PT41CV

 [35032 rows x 3 columns],
                       Time  Energy Location  Energy
 0      2021-11-01 00:15:00   0.028   PT44AL   0.452
 1      2021-11-01 00:30:00   0.080   PT44AL   0.440
 2      2021-11-01 00:45:00   0.092   PT44AL   0.424
 3      2021-11-01 01:00:00   0.040   PT44AL   0.408
 4      2021-11-01 01:15:00   0.076   PT44AL   0.396
 ...                    ...     ...      ...     ...
 35027  2022-10-31 23:00:00   0.120   PT44AL   0.448
 35028  2022-10-31 23:15:00   0.036   PT44AL   0.424
 35029  2022-10-31 23:30:00   0.064   PT44AL   0.392
 35030  2022-10-31 23:45:00   0.132   PT44AL   0.260
 35031  2022-11-01 00:00:00   0.180   PT44AL   0.332

 [35032 rows x 4 columns],
                       Time  Energy Location  Energy  Energy
 0      2021-11-01 00:15:00   0.028   PT15VP   0.452   0.000
 1      2021-11-01 00:30:00   0.080   PT15VP   0.440   0.000
 2      2021-11-01 00:45:00   0.092   PT15VP   0.424   0.000
 3      2021-11-01 01:00:00   0.040   PT15VP   0.408   0.000
 4      2021-11-01 01:15:00   0.076   PT15VP   0.396   0.000
 ...                    ...     ...      ...     ...     ...
 35027  2022-10-31 23:00:00   0.120   PT15VP   0.448   0.108
 35028  2022-10-31 23:15:00   0.036   PT15VP   0.424   0.124
 35029  2022-10-31 23:30:00   0.064   PT15VP   0.392   0.148
 35030  2022-10-31 23:45:00   0.132   PT15VP   0.260   0.132
 35031  2022-11-01 00:00:00   0.180   PT15VP   0.332   0.088

 [35032 rows x 5 columns],
                       Time  Energy Location  Energy  Energy  Energy
 0      2021-11-01 00:15:00   0.028   PT69QG   0.452   0.000   0.828
 1      2021-11-01 00:30:00   0.080   PT69QG   0.440   0.000   0.796
 2      2021-11-01 00:45:00   0.092   PT69QG   0.424   0.000   0.832
 3      2021-11-01 01:00:00   0.040   PT69QG   0.408   0.000   0.800
 4      2021-11-01 01:15:00   0.076   PT69QG   0.396   0.000   0.836
 ...                    ...     ...      ...     ...     ...     ...
 35027  2022-10-31 23:00:00   0.120   PT69QG   0.448   0.108   0.220
 35028  2022-10-31 23:15:00   0.036   PT69QG   0.424   0.124   0.252
 35029  2022-10-31 23:30:00   0.064   PT69QG   0.392   0.148   0.268
 35030  2022-10-31 23:45:00   0.132   PT69QG   0.260   0.132   0.276
 35031  2022-11-01 00:00:00   0.180   PT69QG   0.332   0.088   0.288

 [35032 rows x 6 columns],
                       Time  Energy Location  Energy  Energy  Energy  Energy
 0      2021-11-01 00:15:00   0.028   PT43QL   0.452   0.000   0.828   0.128
 1      2021-11-01 00:30:00   0.080   PT43QL   0.440   0.000   0.796   0.160
 2      2021-11-01 00:45:00   0.092   PT43QL   0.424   0.000   0.832   0.220
 3      2021-11-01 01:00:00   0.040   PT43QL   0.408   0.000   0.800   0.404
 4      2021-11-01 01:15:00   0.076   PT43QL   0.396   0.000   0.836   0.156
 ...                    ...     ...      ...     ...     ...     ...     ...
 35027  2022-10-31 23:00:00   0.120   PT43QL   0.448   0.108   0.220   0.164
 35028  2022-10-31 23:15:00   0.036   PT43QL   0.424   0.124   0.252   0.228
 35029  2022-10-31 23:30:00   0.064   PT43QL   0.392   0.148   0.268   0.224
 35030  2022-10-31 23:45:00   0.132   PT43QL   0.260   0.132   0.276   0.212
 35031  2022-11-01 00:00:00   0.180   PT43QL   0.332   0.088   0.288   0.148

 [35032 rows x 7 columns],
                       Time  Energy Location  Energy  Energy  Energy  Energy  \
 0      2021-11-01 00:15:00   0.028   PT17RW   0.452   0.000   0.828   0.128
 1      2021-11-01 00:30:00   0.080   PT17RW   0.440   0.000   0.796   0.160
 2      2021-11-01 00:45:00   0.092   PT17RW   0.424   0.000   0.832   0.220
 3      2021-11-01 01:00:00   0.040   PT17RW   0.408   0.000   0.800   0.404
 4      2021-11-01 01:15:00   0.076   PT17RW   0.396   0.000   0.836   0.156
 ...                    ...     ...      ...     ...     ...     ...     ...
 35027  2022-10-31 23:00:00   0.120   PT17RW   0.448   0.108   0.220   0.164
 35028  2022-10-31 23:15:00   0.036   PT17RW   0.424   0.124   0.252   0.228
 35029  2022-10-31 23:30:00   0.064   PT17RW   0.392   0.148   0.268   0.224
 35030  2022-10-31 23:45:00   0.132   PT17RW   0.260   0.132   0.276   0.212
 35031  2022-11-01 00:00:00   0.180   PT17RW   0.332   0.088   0.288   0.148

        Energy
 0       0.056
 1       0.056
 2       0.056
 3       0.088
 4       0.116
 ...       ...
 35027   0.144
 35028   0.164
 35029   0.220
 35030   0.176
 35031   0.132

 [35032 rows x 8 columns],
                       Time  Energy Location  Energy  Energy  Energy  Energy  \
 0      2021-11-01 00:15:00   0.028   PT87ZW   0.452   0.000   0.828   0.128
 1      2021-11-01 00:30:00   0.080   PT87ZW   0.440   0.000   0.796   0.160
 2      2021-11-01 00:45:00   0.092   PT87ZW   0.424   0.000   0.832   0.220
 3      2021-11-01 01:00:00   0.040   PT87ZW   0.408   0.000   0.800   0.404
 4      2021-11-01 01:15:00   0.076   PT87ZW   0.396   0.000   0.836   0.156
 ...                    ...     ...      ...     ...     ...     ...     ...
 35027  2022-10-31 23:00:00   0.120   PT87ZW   0.448   0.108   0.220   0.164
 35028  2022-10-31 23:15:00   0.036   PT87ZW   0.424   0.124   0.252   0.228
 35029  2022-10-31 23:30:00   0.064   PT87ZW   0.392   0.148   0.268   0.224
 35030  2022-10-31 23:45:00   0.132   PT87ZW   0.260   0.132   0.276   0.212
 35031  2022-11-01 00:00:00   0.180   PT87ZW   0.332   0.088   0.288   0.148

        Energy  Energy
 0       0.056   0.552
 1       0.056   0.492
 2       0.056   0.308
 3       0.088   0.156
 4       0.116   0.160
 ...       ...     ...
 35027   0.144   0.368
 35028   0.164   0.396
 35029   0.220   0.356
 35030   0.176   0.392
 35031   0.132   0.356

 [35032 rows x 9 columns]]

In [6]:
df_location = house_list[0]
for i in house_list[1:]:
    df_location = pd.concat([df_location, i], axis=0)
df_location.reset_index(drop=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
df_location.to_pickle("df_location.pkl")